using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;

namespace DeliAi.Backend.Services;

public partial class DeliBot
{
  public async Task<bool> LogWrongInfoReport(string response, string name, bool fullyWrong, string howToImprove)
  {
    try
    {
      await using var db = await _dbContextFactory.CreateDbContextAsync();
      db.WrongInfoReports.Add(new WrongInfoReportEntity
      {
        Response = response,
        Name = name,
        FullyWrong = fullyWrong,
        HowToImprove = howToImprove
      });
      await db.SaveChangesAsync();
      return true;
    }
    catch (Exception ex)
    {
      Console.WriteLine($"[Wrong info log error] Could not save wrong-info report: {ex.Message}");
      return false;
    }
  }

  public async Task<List<object>> GetWrongInfoReports()
  {
    try
    {
      await using var db = await _dbContextFactory.CreateDbContextAsync();
      var reports = await db.WrongInfoReports.OrderBy(r => r.Id).ToListAsync();

      return reports.Select(r => new
      {
        response = r.Response,
        fullyWrong = r.FullyWrong,
        howToImprove = r.HowToImprove
      }).Cast<object>().ToList();
    }
    catch (Exception ex)
    {
      Console.WriteLine($"[Wrong info log error] Could not read wrong-info reports: {ex.Message}");
      return new List<object>();
    }
  }

  public async Task<bool> ResolveWrongInfo(string assistantResponse, string correctedInfo)
  {
    try
    {
      await using var db = await _dbContextFactory.CreateDbContextAsync();

      var report = await db.WrongInfoReports.FirstOrDefaultAsync(r => r.Response == assistantResponse);
      if (report == null)
      {
        Console.WriteLine("[Wrong info resolve error] Could not find matching report.");
        return false;
      }

      db.WrongInfoReports.Remove(report);
      await db.SaveChangesAsync();

      // Ask AI which stored fact(s) this bad response likely came from, and remove them
      var sourceFacts = await FindFactsBehindResponseAsync(assistantResponse);

      if (sourceFacts.Count > 0)
      {
        var toRemove = await db.Facts
            .Where(e => e.Info != DefaultRefusalRule && sourceFacts.Contains(e.Info))
            .ToListAsync();
        if (toRemove.Count > 0)
        {
          db.Facts.RemoveRange(toRemove);
          await db.SaveChangesAsync();
        }
      }

      // Add the corrected fact
      await AddFactAsync(correctedInfo);
      await DedupeFactsAsync();

      return true;
    }
    catch (Exception ex)
    {
      Console.WriteLine($"[Wrong info resolve error] {ex.Message}");
      return false;
    }
  }

  private async Task<List<string>> FindFactsBehindResponseAsync(string assistantResponse)
  {
    await using var db = await _dbContextFactory.CreateDbContextAsync();
    var facts = await db.Facts.Where(e => e.Info != DefaultRefusalRule).ToListAsync();

    string factList = string.Join("\n", facts.Select(e => $"- {e.Info}"));

    string systemPrompt =
        "You are helping maintain a deli assistant bot's knowledge base.\n\n" +
        "The bot previously gave a customer the ASSISTANT RESPONSE below. That response was generated by " +
        "the bot picking one or more facts from its knowledge base and repeating/lightly rephrasing them. " +
        "A user has reported that response as wrong or incomplete, and it needs to be corrected.\n\n" +
        "Your job: identify EXACTLY which fact(s) in the CURRENT KNOWN FACTS list the bot most likely used " +
        "to generate that response — the source fact(s) that need to be fixed or removed. Be conservative: " +
        "only include a fact if it's clearly and specifically the source of that response, not merely " +
        "related or topically similar.\n\n" +
        $"CURRENT KNOWN FACTS:\n{factList}\n\n" +
        $"ASSISTANT RESPONSE:\n{assistantResponse}\n\n" +
        "Respond with ONLY a JSON object shaped exactly like this, nothing else — no markdown, no " +
        "backticks, no preamble:\n" +
        "{\n" +
        "  \"sourceFacts\": [\"<fact(s) from CURRENT KNOWN FACTS, copied verbatim, that are the source of " +
        "the response>\"]\n" +
        "}";

    var requestBody = new
    {
      contents = new[]
      {
      new { role = "user", parts = new[] { new { text = "Identify the source fact(s)." } } }
    },
      systemInstruction = new
      {
        parts = new[] { new { text = systemPrompt } }
      }
    };

    string json = JsonSerializer.Serialize(requestBody);
    var content = new StringContent(json, Encoding.UTF8, "application/json");
    string url = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key={_apiKey}";

    try
    {
      var response = await _http.PostAsync(url, content);
      string responseText = await response.Content.ReadAsStringAsync();

      if (!response.IsSuccessStatusCode)
      {
        Console.WriteLine($"[Find source fact error] Gemini API returned failure: {responseText}");
        return new List<string>();
      }

      using var doc = JsonDocument.Parse(responseText);
      var answer = doc.RootElement
          .GetProperty("candidates")[0]
          .GetProperty("content")
          .GetProperty("parts")[0]
          .GetProperty("text")
          .GetString();

      string cleaned = (answer ?? "{}").Trim();
      if (cleaned.StartsWith("```"))
      {
        int firstNewline = cleaned.IndexOf('\n');
        int lastFence = cleaned.LastIndexOf("```");
        if (firstNewline >= 0 && lastFence > firstNewline)
          cleaned = cleaned.Substring(firstNewline + 1, lastFence - firstNewline - 1).Trim();
      }

      using var resultDoc = JsonDocument.Parse(cleaned);
      var root = resultDoc.RootElement;

      return root.TryGetProperty("sourceFacts", out var sf)
          ? sf.EnumerateArray().Select(x => x.GetString() ?? "").Where(s => s != "").ToList()
          : new List<string>();
    }
    catch (Exception ex)
    {
      Console.WriteLine($"[Find source fact error] {ex.Message}");
      return new List<string>();
    }
  }

  public async Task<bool> DismissWrongInfoReport(string response)
  {
    try
    {
      await using var db = await _dbContextFactory.CreateDbContextAsync();
      var report = await db.WrongInfoReports.FirstOrDefaultAsync(r => r.Response == response);

      if (report == null)
      {
        Console.WriteLine("[Wrong info dismiss error] Could not find matching report.");
        return false;
      }

      db.WrongInfoReports.Remove(report);
      await db.SaveChangesAsync();
      return true;
    }
    catch (Exception ex)
    {
      Console.WriteLine($"[Wrong info dismiss error] {ex.Message}");
      return false;
    }
  }
}
